### ISSUE TITLE
Compacting segments: nil pointer dereference

### ISSUE THREAD

**Issue by au-phiware** [creativecreature/pulse#4]
Thank you for this project, I hope it may become useful to myself, at least.

I have setup a systemd service for the pulse-service but it segfaults every 5 minutes:

```
Jun 19 21:43:26 euler pulse-server[1492679]: INFO Compacting segments
Jun 19 21:43:26 euler pulse-server[1492679]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 19 21:43:26 euler pulse-server[1492679]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c73c0]
Jun 19 21:43:26 euler pulse-server[1492679]: goroutine 11 [running]:
Jun 19 21:43:26 euler pulse-server[1492679]: github.com/creativecreature/pulse.(*LogDB).compact(0xc00003f800)
Jun 19 21:43:26 euler pulse-server[1492679]:         github.com/creativecreature/pulse/logdb.go:140 +0x140
Jun 19 21:43:26 euler pulse-server[1492679]: github.com/creativecreature/pulse.NewDB.func1.1()
Jun 19 21:43:26 euler pulse-server[1492679]:         github.com/creativecreature/pulse/logdb.go:55 +0x45
Jun 19 21:43:26 euler pulse-server[1492679]: created by github.com/creativecreature/pulse.NewDB.func1 in goroutine 1
Jun 19 21:43:26 euler pulse-server[1492679]:         github.com/creativecreature/pulse/logdb.go:51 +0x56
```

It appears to be cause by this line: https://github.com/creativecreature/pulse/blob/bc4b6dacaf7c2cec37b95de014e2c5785e20610e/logdb.go#L140

I may find time to debug it further, but I thought you'd like to know.

**Comment by creativecreature** [comment]
Hi, thank you so much for taking the time to open this issue! 

I had noticed this too and I believe that I fixed it in this PR https://github.com/creativecreature/pulse/pull/5. Could you test with the latest `main` to see if it still occurs?

**Comment by au-phiware** [comment]
Can confirm, this has fixed the issue, thanks!
